from __future__ import annotations

"""
AH-1S / JSBSim
STAGE 3 HYBRID FINAL BUILD V3
=============================

Method
------
1) Use the already locked Stage-1 neural policy.
2) Use the already locked Stage-2 HYBRID FINAL neural policy.
3) Reproduce the true continuous Stage1 -> Stage2 -> Stage3 handoff.
4) Reproduce the locked Stage-3 teacher:
      - unchanged altitude controller
      - unchanged longitudinal endpoint controller
      - data-grounded lateral controller
5) Build a dedicated Stage-3 observation that includes the mission geometry
   actually required by the teacher (forward position error and cross-track).
6) Collect teacher state-action data, including small off-trajectory recovery
   samples generated by perturbing the APPLIED action while keeping the
   teacher label exact.
7) Behavior-clone the complete four-action teacher into a fresh PPO actor.
8) Validate the BC policy with teacher OFF on a fresh true continuous flight.
9) Fine-tune the BC policy with genuine reward-based PPO updates in a
   dedicated Stage-3 environment; no teacher/controller is used at runtime.
10) Validate each RL candidate teacher OFF on the true continuous
    Stage1 -> Stage2 -> Stage3 JSBSim mission.
11) Save only a passing PPO-refined Stage-3 model.

Important terminology
---------------------
- Behavior cloning / distillation is supervised policy learning, NOT RL.
- The later PPO .learn(...) phase IS reward-based reinforcement learning.
- The final model is accepted only if the runtime teacher is OFF.

The Stage-3 model is intentionally a separate policy from Stage 2 because
Stage 3 is a different control phase and requires endpoint geometry in its
observation.
"""

import csv
import json
import math
import random
from pathlib import Path

import gymnasium as gym
from gymnasium import spaces
import numpy as np
import torch
import torch.nn as nn
from stable_baselines3 import PPO
from stable_baselines3.common.monitor import Monitor

from helicopter_env_stage1_distill import HelicopterEnvStage1Distill
from helicopter_env_stage2_refine_mapped import HelicopterEnvStage2RefineMapped


# =====================================================================
# PATHS
# =====================================================================

STAGE1_MODEL_PATH = Path(
    "models_stage1_early_distilled/"
    "AH1S_STAGE1_EARLY_DISTILLED.zip"
)

STAGE2_MODEL_PATH = Path(
    "models_stage2_hybrid_final/"
    "AH1S_STAGE2_HYBRID_FINAL.zip"
)

TEACHER_SUMMARY_PATH = Path(
    "results_stage3_lateral_teacher_v3/"
    "final_summary.json"
)

MODEL_DIR = Path(
    "models_stage3_hybrid_final"
)

RESULT_DIR = Path(
    "results_stage3_hybrid_final"
)

MODEL_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

RESULT_DIR.mkdir(
    parents=True,
    exist_ok=True,
)

BC_MODEL_PATH = (
    MODEL_DIR
    /
    "AH1S_STAGE3_BC_WARMSTART"
)

FINAL_MODEL_PATH = (
    MODEL_DIR
    /
    "AH1S_STAGE3_HYBRID_FINAL"
)


for required in [
    STAGE1_MODEL_PATH,
    STAGE2_MODEL_PATH,
    TEACHER_SUMMARY_PATH,
]:
    if not required.exists():
        raise FileNotFoundError(
            f"Required input missing: {required}"
        )


# =====================================================================
# REPRODUCIBILITY
# =====================================================================

SEED = 42

random.seed(
    SEED
)

np.random.seed(
    SEED
)

torch.manual_seed(
    SEED
)

rng = np.random.default_rng(
    SEED
)


# =====================================================================
# MISSION CONSTANTS
# =====================================================================

TARGET_FORWARD_FT = 300.0
TARGET_ALT_FT = 300.0

STAGE1_MAX_TIME = 120.0
STAGE2_MAX_TIME = 55.0
STAGE3_MAX_TIME = 90.0

HANDOFF_STABLE_TIME = 5.0
DEFAULT_CONTROL_DT = 0.075

# Stage-3 policy takes over after the locked Stage-2 cruise has flown 80 ft.
STAGE3_TAKEOVER_FORWARD_FT = 80.0

AILERON_SCALE = 0.026
RUDDER_SCALE = 0.040

EARTH_RADIUS_FT = 20_902_231.0


# =====================================================================
# LOCKED STAGE-3 TEACHER PARAMETERS
# Read from the successfully calibrated V3 summary where possible.
# =====================================================================

with TEACHER_SUMMARY_PATH.open(
    "r",
    encoding="utf-8",
) as f:
    teacher_summary = json.load(
        f
    )


locked_teacher = teacher_summary.get(
    "final_teacher",
    {},
)

if not bool(
    locked_teacher.get(
        "teacher_pass",
        False,
    )
):
    raise RuntimeError(
        "Stage-3 teacher summary is not a passing locked teacher."
    )


# Existing Stage-3 altitude teacher.
COLLECTIVE_BIAS = 0.22
ALT_KP = 0.030
VS_KD = 0.120
MAX_ALT_CORR = 0.45

# Existing Stage-3 longitudinal teacher.
K_POS = 0.055
V_FWD_MAX = 9.0
BRAKE_LEAD_FT = 8.0
V_REV_MAX = 2.0
KV = 1.00
ELEVATOR_TRIM_ACTION = 0.013725
Q_DAMP = 2.0
MAX_ELEVATOR_RESIDUAL = 1.0

# Locked Stage-3 lateral teacher from V3.
LATERAL_ENABLE_FORWARD_FT = float(
    locked_teacher[
        "activation_forward_ft"
    ]
)

HOVER_TRIM = float(
    locked_teacher[
        "hover_trim"
    ]
)

LATERAL_KP = float(
    locked_teacher[
        "lateral_kp"
    ]
)

LATERAL_KD = float(
    locked_teacher[
        "lateral_kd"
    ]
)

# V2 identified/tested action[2] physical authority envelope.
diagnostic_evidence = teacher_summary.get(
    "diagnostic_evidence",
    {},
)

IDENTIFIED_A2_MIN = float(
    diagnostic_evidence.get(
        "identified_action2_min",
        -0.630,
    )
)

IDENTIFIED_A2_MAX = float(
    diagnostic_evidence.get(
        "identified_action2_max",
        +0.170,
    )
)

CRUISE_AILERON_ACTION = -0.230
RUDDER_ACTION = 0.0


# =====================================================================
# ACCEPTANCE / SAFETY
# =====================================================================

STOP_POS_TOL_FT = 5.0
STOP_SPEED_TOL_FPS = 0.60
STOP_HOLD_SECONDS = 5.0

CROSS_TOL_FT = 5.0
LAT_SPEED_TOL_FPS = 0.60

ALT_MIN = 295.0
ALT_MAX = 305.0
VS_TOL_FPS = 0.75
HEADING_TOL_DEG = 1.0

# Entire Stage-3 presentation corridor.
PRESENTATION_MAX_CROSS_FT = 5.0
PRESENTATION_ALT_MIN = 295.0
PRESENTATION_ALT_MAX = 305.0

# Wider safety envelope.
ALT_SAFE_MIN = 288.0
ALT_SAFE_MAX = 312.0
MAX_ABS_PITCH_DEG = 8.0
MAX_ABS_ROLL_DEG = 10.0
MAX_CROSS_SAFE_FT = 15.0


# =====================================================================
# DISTILLATION / PPO SETTINGS
# =====================================================================

DATA_ROLLOUTS = 7

# Applied-action perturbations for recovery-state collection.
# The stored label always remains the exact teacher action.
DATA_ACTION_NOISE_STD = [
    0.000,
    0.010,
    0.015,
    0.020,
    0.025,
    0.015,
    0.010,
]

BC_EPOCHS = 320
BC_BATCH_SIZE = 256
BC_LR = 8e-4

RL_EXPLORATION_STD = 0.03

RL_CANDIDATES = [
    # learning rate, timesteps
    (1e-6, 1024),
    (2e-6, 2048),
    (5e-6, 2048),
    (1e-5, 2048),
]


# =====================================================================
# HELPERS
# =====================================================================

def rule(
    text,
):
    print()
    print(
        "=" * 154
    )
    print(
        text
    )
    print(
        "=" * 154
    )


def fdm_float(
    fdm,
    key,
    default=float(
        "nan"
    ),
):
    try:
        return float(
            fdm[
                key
            ]
        )
    except Exception:
        return float(
            default
        )


def first_finite(
    fdm,
    keys,
    default=float(
        "nan"
    ),
):
    for key in keys:
        value = fdm_float(
            fdm,
            key,
        )

        if np.isfinite(
            value
        ):
            return value

    return float(
        default
    )


def info_float(
    info,
    key,
    default=float(
        "nan"
    ),
):
    try:
        return float(
            info.get(
                key,
                default,
            )
        )
    except Exception:
        return float(
            default
        )


def get_fdm(
    env,
):
    if getattr(
        env,
        "fdm",
        None,
    ) is not None:
        return env.fdm

    base = getattr(
        env,
        "base_env",
        None,
    )

    if (
        base is not None
        and getattr(
            base,
            "fdm",
            None,
        )
        is not None
    ):
        return base.fdm

    raise RuntimeError(
        "Active FDM not found."
    )


def latitude_deg(
    fdm,
):
    return first_finite(
        fdm,
        [
            "position/lat-gc-deg",
            "position/lat-geod-deg",
        ],
    )


def longitude_deg(
    fdm,
):
    return first_finite(
        fdm,
        [
            "position/long-gc-deg",
            "position/long-geod-deg",
        ],
    )


def heading_rad(
    fdm,
):
    return first_finite(
        fdm,
        [
            "attitude/heading-true-rad",
            "attitude/psi-rad",
        ],
    )


def wrap_angle(
    value,
):
    return math.atan2(
        math.sin(
            value
        ),
        math.cos(
            value
        ),
    )


def local_ne_ft(
    lat,
    lon,
    lat0,
    lon0,
):
    dlat = math.radians(
        lat
        -
        lat0
    )

    dlon = math.radians(
        lon
        -
        lon0
    )

    north = (
        EARTH_RADIUS_FT
        *
        dlat
    )

    east = (
        EARTH_RADIUS_FT
        *
        math.cos(
            math.radians(
                lat0
            )
        )
        *
        dlon
    )

    return (
        float(
            north
        ),
        float(
            east
        ),
    )


def mission_axes(
    north,
    east,
    heading,
):
    c = math.cos(
        heading
    )

    s = math.sin(
        heading
    )

    forward = (
        north
        *
        c
        +
        east
        *
        s
    )

    cross = (
        -north
        *
        s
        +
        east
        *
        c
    )

    return (
        float(
            forward
        ),
        float(
            cross
        ),
    )


def geometry(
    fdm,
    lat0,
    lon0,
    mission_heading,
):
    north, east = (
        local_ne_ft(
            latitude_deg(
                fdm
            ),
            longitude_deg(
                fdm
            ),
            lat0,
            lon0,
        )
    )

    return mission_axes(
        north,
        east,
        mission_heading,
    )


def mission_ground_velocity(
    fdm,
    mission_heading,
):
    vn = first_finite(
        fdm,
        [
            "velocities/v-north-fps",
        ],
    )

    ve = first_finite(
        fdm,
        [
            "velocities/v-east-fps",
        ],
    )

    if (
        not np.isfinite(
            vn
        )
        or
        not np.isfinite(
            ve
        )
    ):
        return (
            float(
                "nan"
            ),
            float(
                "nan"
            ),
        )

    return mission_axes(
        vn,
        ve,
        mission_heading,
    )


def physical_commands(
    fdm,
):
    return {
        "physical_collective_cmd":
            fdm_float(
                fdm,
                "fcs/collective-cmd-norm",
            ),

        "physical_elevator_cmd":
            fdm_float(
                fdm,
                "fcs/elevator-cmd-norm",
            ),

        "physical_aileron_cmd":
            fdm_float(
                fdm,
                "fcs/aileron-cmd-norm",
            ),

        "physical_rudder_cmd":
            fdm_float(
                fdm,
                "fcs/rudder-cmd-norm",
            ),
    }


def snapshot(
    fdm,
    lat0,
    lon0,
    mission_heading,
):
    forward, cross = geometry(
        fdm,
        lat0,
        lon0,
        mission_heading,
    )

    heading_error = wrap_angle(
        heading_rad(
            fdm
        )
        -
        mission_heading
    )

    ground_fwd, ground_cross = (
        mission_ground_velocity(
            fdm,
            mission_heading,
        )
    )

    state = {
        "forward_ft":
            float(
                forward
            ),

        "position_error_ft":
            float(
                TARGET_FORWARD_FT
                -
                forward
            ),

        "cross_track_ft":
            float(
                cross
            ),

        "altitude_ft":
            fdm_float(
                fdm,
                "position/h-agl-ft",
            ),

        "forward_speed_fps":
            fdm_float(
                fdm,
                "velocities/u-aero-fps",
                0.0,
            ),

        "lateral_speed_fps":
            fdm_float(
                fdm,
                "velocities/v-aero-fps",
                0.0,
            ),

        "mission_ground_forward_speed_fps":
            float(
                ground_fwd
            ),

        "mission_ground_cross_speed_fps":
            float(
                ground_cross
            ),

        "vertical_speed_fps":
            fdm_float(
                fdm,
                "velocities/h-dot-fps",
                0.0,
            ),

        "heading_error_rad":
            float(
                heading_error
            ),

        "heading_error_deg":
            math.degrees(
                heading_error
            ),

        "pitch_rad":
            fdm_float(
                fdm,
                "attitude/pitch-rad",
                0.0,
            ),

        "roll_rad":
            fdm_float(
                fdm,
                "attitude/roll-rad",
                0.0,
            ),

        "roll_rate_rad_s":
            fdm_float(
                fdm,
                "velocities/p-rad_sec",
                0.0,
            ),

        "pitch_rate_rad_s":
            fdm_float(
                fdm,
                "velocities/q-rad_sec",
                0.0,
            ),

        "yaw_rate_rad_s":
            fdm_float(
                fdm,
                "velocities/r-rad_sec",
                0.0,
            ),

        "rotor_rpm":
            fdm_float(
                fdm,
                "propulsion/engine/rotor-rpm",
                323.0,
            ),
    }

    state.update(
        physical_commands(
            fdm
        )
    )

    return state


def stage3_observation(
    state,
):
    """
    Dedicated Stage-3 observation.

    It includes the mission geometry that the endpoint controller actually
    needs. All entries are scaled to approximately O(1).
    """

    obs = np.array(
        [
            # 0 altitude error
            (
                state[
                    "altitude_ft"
                ]
                -
                TARGET_ALT_FT
            )
            /
            10.0,

            # 1 vertical speed
            state[
                "vertical_speed_fps"
            ]
            /
            5.0,

            # 2 forward position error
            state[
                "position_error_ft"
            ]
            /
            250.0,

            # 3 forward speed
            state[
                "forward_speed_fps"
            ]
            /
            12.0,

            # 4 cross-track
            state[
                "cross_track_ft"
            ]
            /
            10.0,

            # 5 lateral speed
            state[
                "lateral_speed_fps"
            ]
            /
            5.0,

            # 6-7 continuous heading representation
            math.sin(
                state[
                    "heading_error_rad"
                ]
            ),

            math.cos(
                state[
                    "heading_error_rad"
                ]
            ),

            # 8 pitch
            state[
                "pitch_rad"
            ]
            /
            0.20,

            # 9 roll
            state[
                "roll_rad"
            ]
            /
            0.20,

            # 10 roll rate
            state[
                "roll_rate_rad_s"
            ]
            /
            1.0,

            # 11 pitch rate
            state[
                "pitch_rate_rad_s"
            ]
            /
            1.0,

            # 12 yaw rate
            state[
                "yaw_rate_rad_s"
            ]
            /
            1.0,

            # 13 rotor RPM
            state[
                "rotor_rpm"
            ]
            /
            400.0,
        ],
        dtype=np.float32,
    )

    return np.clip(
        obs,
        -10.0,
        +10.0,
    ).astype(
        np.float32
    )


def safety_reason(
    state,
):
    if (
        state[
            "altitude_ft"
        ]
        <
        ALT_SAFE_MIN
    ):
        return (
            "altitude_below_safe"
        )

    if (
        state[
            "altitude_ft"
        ]
        >
        ALT_SAFE_MAX
    ):
        return (
            "altitude_above_safe"
        )

    if (
        abs(
            math.degrees(
                state[
                    "pitch_rad"
                ]
            )
        )
        >
        MAX_ABS_PITCH_DEG
    ):
        return (
            "pitch_limit"
        )

    if (
        abs(
            math.degrees(
                state[
                    "roll_rad"
                ]
            )
        )
        >
        MAX_ABS_ROLL_DEG
    ):
        return (
            "roll_limit"
        )

    if (
        abs(
            state[
                "cross_track_ft"
            ]
        )
        >
        MAX_CROSS_SAFE_FT
    ):
        return (
            "cross_track_safety_limit"
        )

    return ""


def endpoint_stop_now(
    state,
):
    return bool(
        abs(
            state[
                "position_error_ft"
            ]
        )
        <=
        STOP_POS_TOL_FT
        and
        abs(
            state[
                "forward_speed_fps"
            ]
        )
        <=
        STOP_SPEED_TOL_FPS
    )


def endpoint_lateral_now(
    state,
):
    return bool(
        abs(
            state[
                "cross_track_ft"
            ]
        )
        <=
        CROSS_TOL_FT
        and
        abs(
            state[
                "lateral_speed_fps"
            ]
        )
        <=
        LAT_SPEED_TOL_FPS
    )


def endpoint_hover_now(
    state,
):
    return bool(
        endpoint_stop_now(
            state
        )
        and
        endpoint_lateral_now(
            state
        )
        and
        ALT_MIN
        <=
        state[
            "altitude_ft"
        ]
        <=
        ALT_MAX
        and
        abs(
            state[
                "vertical_speed_fps"
            ]
        )
        <=
        VS_TOL_FPS
        and
        abs(
            state[
                "heading_error_deg"
            ]
        )
        <=
        HEADING_TOL_DEG
    )


def env_control_dt(
    env,
):
    dt = float(
        getattr(
            env,
            "dt",
            DEFAULT_CONTROL_DT,
        )
        or
        DEFAULT_CONTROL_DT
    )

    if (
        not np.isfinite(
            dt
        )
        or
        dt
        <=
        0.0
    ):
        dt = (
            DEFAULT_CONTROL_DT
        )

    return dt


def physics_steps(
    env,
):
    value = getattr(
        env,
        "PHYSICS_STEPS",
        10,
    )

    try:
        value = int(
            value
        )
    except Exception:
        value = 10

    return max(
        1,
        value,
    )


# =====================================================================
# LOCKED MODELS
# =====================================================================

stage1_model = PPO.load(
    str(
        STAGE1_MODEL_PATH
    )
)

stage2_model = PPO.load(
    str(
        STAGE2_MODEL_PATH
    )
)


# =====================================================================
# TRUE CONTINUOUS STAGE1 -> STAGE2 -> STAGE3 START
# =====================================================================

def build_stage3_start():
    env1 = (
        HelicopterEnvStage1Distill(
            teacher_model_path=None,
            training_mode=False,
        )
    )

    obs1, info1 = (
        env1.reset()
    )

    fdm = get_fdm(
        env1
    )

    active_fdm_id = id(
        fdm
    )

    mission_heading = heading_rad(
        fdm
    )

    dt1 = env_control_dt(
        env1
    )

    stable_time = 0.0

    for _ in range(
        int(
            STAGE1_MAX_TIME
            /
            dt1
        )
    ):
        action1, _ = (
            stage1_model.predict(
                obs1,
                deterministic=True,
            )
        )

        (
            obs1,
            _,
            terminated,
            truncated,
            info1,
        ) = env1.step(
            action1
        )

        altitude = info_float(
            info1,
            "altitude",
        )

        vertical_speed = info_float(
            info1,
            "vertical_speed",
        )

        vn = info_float(
            info1,
            "vn",
            0.0,
        )

        ve = info_float(
            info1,
            "ve",
            0.0,
        )

        horizontal_speed = float(
            np.hypot(
                vn,
                ve,
            )
        )

        drift = info_float(
            info1,
            "drift",
            999.0,
        )

        stable = bool(
            295.0
            <=
            altitude
            <=
            305.0
            and
            abs(
                vertical_speed
            )
            <=
            0.50
            and
            horizontal_speed
            <=
            1.0
            and
            drift
            <=
            3.0
        )

        stable_time = (
            stable_time
            +
            dt1
            if stable
            else
            0.0
        )

        if (
            stable_time
            >=
            HANDOFF_STABLE_TIME
        ):
            break

        if (
            terminated
            and
            not bool(
                info1.get(
                    "success",
                    False,
                )
            )
        ):
            env1.close()

            raise RuntimeError(
                "Stage 1 failed before stable handoff."
            )

        if truncated:
            env1.close()

            raise RuntimeError(
                "Stage 1 truncated before stable handoff."
            )

    if (
        stable_time
        <
        HANDOFF_STABLE_TIME
    ):
        env1.close()

        raise RuntimeError(
            "Stable Stage-1 handoff was not reached."
        )

    # Mission geometry origin is the true Stage-1 hover handoff.
    lat0 = latitude_deg(
        fdm
    )

    lon0 = longitude_deg(
        fdm
    )

    sim_time_before_attach = first_finite(
        fdm,
        [
            "simulation/sim-time-sec",
        ],
    )

    env2 = (
        HelicopterEnvStage2RefineMapped(
            aileron_scale=
                AILERON_SCALE,

            rudder_scale=
                RUDDER_SCALE,
        )
    )

    # Disposable reset initializes Python bookkeeping only.
    env2.reset()

    env2.fdm = (
        fdm
    )

    if hasattr(
        env2,
        "forward_distance",
    ):
        env2.forward_distance = (
            0.0
        )

    if hasattr(
        env2,
        "target_heading",
    ):
        env2.target_heading = float(
            mission_heading
        )

    for attr in [
        "steps",
        "target_hold_steps",
        "hold_steps",
        "success_hold_steps",
    ]:
        if hasattr(
            env2,
            attr,
        ):
            setattr(
                env2,
                attr,
                0,
            )

    if (
        id(
            get_fdm(
                env2
            )
        )
        !=
        active_fdm_id
    ):
        env2.fdm = None
        env1.close()

        raise RuntimeError(
            "FDM continuity failed."
        )

    sim_time_after_attach = first_finite(
        fdm,
        [
            "simulation/sim-time-sec",
        ],
    )

    if (
        np.isfinite(
            sim_time_before_attach
        )
        and
        np.isfinite(
            sim_time_after_attach
        )
        and
        abs(
            sim_time_after_attach
            -
            sim_time_before_attach
        )
        >
        1e-9
    ):
        env2.fdm = None
        env1.close()

        raise RuntimeError(
            "Simulation clock changed during Stage-2 attach."
        )

    obs2 = np.asarray(
        env2._get_obs(),
        dtype=np.float32,
    )

    dt2 = env_control_dt(
        env2
    )

    for _ in range(
        int(
            STAGE2_MAX_TIME
            /
            dt2
        )
    ):
        action2, _ = (
            stage2_model.predict(
                obs2,
                deterministic=True,
            )
        )

        action2 = np.asarray(
            action2,
            dtype=np.float32,
        ).reshape(
            -1
        )

        (
            obs2,
            _,
            terminated,
            truncated,
            info2,
        ) = env2.step(
            action2
        )

        obs2 = np.asarray(
            obs2,
            dtype=np.float32,
        )

        forward, _cross = geometry(
            fdm,
            lat0,
            lon0,
            mission_heading,
        )

        if (
            forward
            >=
            STAGE3_TAKEOVER_FORWARD_FT
        ):
            if hasattr(
                env2,
                "forward_distance",
            ):
                env2.forward_distance = float(
                    forward
                )

            break

        if (
            terminated
            and
            not bool(
                info2.get(
                    "success",
                    False,
                )
            )
        ):
            env2.fdm = None
            env1.close()

            raise RuntimeError(
                "Stage 2 failed before Stage-3 takeover."
            )

        if truncated:
            env2.fdm = None
            env1.close()

            raise RuntimeError(
                "Stage 2 truncated before Stage-3 takeover."
            )

    state = snapshot(
        fdm,
        lat0,
        lon0,
        mission_heading,
    )

    return {
        "env1":
            env1,

        "env2":
            env2,

        "fdm":
            fdm,

        "stage2_obs":
            obs2,

        "lat0":
            lat0,

        "lon0":
            lon0,

        "mission_heading":
            mission_heading,

        "active_fdm_id":
            active_fdm_id,

        "state":
            state,
    }


# =====================================================================
# LOCKED TEACHER ACTION
# =====================================================================

def locked_teacher_action(
    stage2_obs,
    state,
):
    base_action, _ = (
        stage2_model.predict(
            stage2_obs,
            deterministic=True,
        )
    )

    base_action = np.asarray(
        base_action,
        dtype=np.float32,
    ).reshape(
        -1
    )

    action = (
        base_action.copy()
    )

    # Altitude teacher.
    altitude_error = (
        TARGET_ALT_FT
        -
        state[
            "altitude_ft"
        ]
    )

    collective_correction = (
        COLLECTIVE_BIAS
        +
        ALT_KP
        *
        altitude_error
        -
        VS_KD
        *
        state[
            "vertical_speed_fps"
        ]
    )

    collective_correction = float(
        np.clip(
            collective_correction,
            -MAX_ALT_CORR,
            +MAX_ALT_CORR,
        )
    )

    action[0] = float(
        np.clip(
            base_action[0]
            +
            collective_correction,
            -1.0,
            +1.0,
        )
    )

    # Longitudinal endpoint teacher.
    v_des = float(
        np.clip(
            K_POS
            *
            (
                state[
                    "position_error_ft"
                ]
                -
                BRAKE_LEAD_FT
            ),
            -V_REV_MAX,
            +V_FWD_MAX,
        )
    )

    speed_error = (
        state[
            "forward_speed_fps"
        ]
        -
        v_des
    )

    elevator_residual = (
        -KV
        *
        speed_error
        +
        Q_DAMP
        *
        state[
            "pitch_rate_rad_s"
        ]
    )

    elevator_residual = float(
        np.clip(
            elevator_residual,
            -MAX_ELEVATOR_RESIDUAL,
            +MAX_ELEVATOR_RESIDUAL,
        )
    )

    action[1] = float(
        np.clip(
            ELEVATOR_TRIM_ACTION
            +
            elevator_residual,
            -1.0,
            +1.0,
        )
    )

    # Data-grounded lateral teacher.
    lateral_active = bool(
        state[
            "forward_ft"
        ]
        >=
        LATERAL_ENABLE_FORWARD_FT
    )

    if lateral_active:
        lateral_correction = (
            -LATERAL_KP
            *
            state[
                "cross_track_ft"
            ]
            -
            LATERAL_KD
            *
            state[
                "lateral_speed_fps"
            ]
        )

        action[2] = float(
            np.clip(
                HOVER_TRIM
                +
                lateral_correction,
                IDENTIFIED_A2_MIN,
                IDENTIFIED_A2_MAX,
            )
        )

    else:
        action[2] = (
            CRUISE_AILERON_ACTION
        )

    action[3] = (
        RUDDER_ACTION
    )

    return np.clip(
        action,
        -1.0,
        +1.0,
    ).astype(
        np.float32
    )


# =====================================================================
# STAGE-3 TRAINING ENVIRONMENT
# =====================================================================

class HelicopterEnvStage3Hybrid(
    gym.Env
):
    """
    Dedicated Stage-3 environment.

    reset():
        physically reproduces the locked Stage1 -> Stage2 flight and returns
        the true Stage-3 start at ~80 ft forward.

    step(action):
        applies the four neural actions directly through the mapped Stage-2
        actuator path, advances the SAME JSBSim FDM, computes a mission reward,
        and terminates only on Stage-3 success/failure.

    No teacher/controller is used in step().
    """

    metadata = {
        "render_modes": [],
    }

    def __init__(
        self,
    ):
        super().__init__()

        self.action_space = (
            spaces.Box(
                low=-1.0,
                high=+1.0,
                shape=(
                    4,
                ),
                dtype=np.float32,
            )
        )

        self.observation_space = (
            spaces.Box(
                low=np.full(
                    14,
                    -10.0,
                    dtype=np.float32,
                ),
                high=np.full(
                    14,
                    +10.0,
                    dtype=np.float32,
                ),
                dtype=np.float32,
            )
        )

        self.env1 = None
        self.env2 = None
        self.fdm = None

        self.stage2_obs = None

        self.lat0 = None
        self.lon0 = None
        self.mission_heading = None

        self.dt = (
            DEFAULT_CONTROL_DT
        )

        self.steps = 0
        self.max_steps = int(
            STAGE3_MAX_TIME
            /
            self.dt
        )

        self.hover_hold_s = 0.0

        self.previous_abs_position_error = None
        self.previous_action = np.zeros(
            4,
            dtype=np.float32,
        )

        self.last_state = None

    def _close_current(
        self,
    ):
        if self.env2 is not None:
            try:
                self.env2.fdm = None
            except Exception:
                pass

        if self.env1 is not None:
            try:
                self.env1.close()
            except Exception:
                pass

        self.env1 = None
        self.env2 = None
        self.fdm = None
        self.stage2_obs = None

    def reset(
        self,
        seed=None,
        options=None,
    ):
        super().reset(
            seed=seed,
        )

        self._close_current()

        start = build_stage3_start()

        self.env1 = start[
            "env1"
        ]

        self.env2 = start[
            "env2"
        ]

        self.fdm = start[
            "fdm"
        ]

        self.stage2_obs = np.asarray(
            start[
                "stage2_obs"
            ],
            dtype=np.float32,
        )

        self.lat0 = float(
            start[
                "lat0"
            ]
        )

        self.lon0 = float(
            start[
                "lon0"
            ]
        )

        self.mission_heading = float(
            start[
                "mission_heading"
            ]
        )

        self.dt = env_control_dt(
            self.env2
        )

        self.max_steps = int(
            STAGE3_MAX_TIME
            /
            self.dt
        )

        self.steps = 0
        self.hover_hold_s = 0.0

        self.previous_action = np.zeros(
            4,
            dtype=np.float32,
        )

        state = snapshot(
            self.fdm,
            self.lat0,
            self.lon0,
            self.mission_heading,
        )

        self.last_state = (
            state.copy()
        )

        self.previous_abs_position_error = abs(
            state[
                "position_error_ft"
            ]
        )

        return (
            stage3_observation(
                state
            ),
            self._info(
                state,
                success=False,
                termination_reason="",
            ),
        )

    def _apply_action(
        self,
        action,
    ):
        action = np.asarray(
            action,
            dtype=np.float32,
        ).reshape(
            -1
        )

        action = np.clip(
            action,
            -1.0,
            +1.0,
        ).astype(
            np.float32
        )

        # Use the repaired actuator mapping.
        self.env2._apply_action(
            action
        )

        for _ in range(
            physics_steps(
                self.env2
            )
        ):
            if not self.fdm.run():
                raise RuntimeError(
                    "JSBSim stopped during Stage-3 training."
                )

        if hasattr(
            self.env2,
            "previous_action",
        ):
            try:
                self.env2.previous_action = (
                    action.copy()
                )
            except Exception:
                pass

        if hasattr(
            self.env2,
            "steps",
        ):
            try:
                self.env2.steps += 1
            except Exception:
                pass

        # IMPORTANT:
        # Do not refresh Stage-2 observation here. The original locked
        # Stage-3 V3 loop first updates env2.forward_distance from the TRUE
        # inertial mission geometry, then calls _get_obs(). Reversing that
        # order leaves Stage-2 bookkeeping stale and changes the neural
        # base action used by the teacher.
        return action

    def _info(
        self,
        state,
        success,
        termination_reason,
    ):
        return {
            "success":
                bool(
                    success
                ),

            "termination_reason":
                str(
                    termination_reason
                ),

            "forward_ft":
                float(
                    state[
                        "forward_ft"
                    ]
                ),

            "position_error_ft":
                float(
                    state[
                        "position_error_ft"
                    ]
                ),

            "forward_speed_fps":
                float(
                    state[
                        "forward_speed_fps"
                    ]
                ),

            "cross_track_ft":
                float(
                    state[
                        "cross_track_ft"
                    ]
                ),

            "lateral_speed_fps":
                float(
                    state[
                        "lateral_speed_fps"
                    ]
                ),

            "altitude_ft":
                float(
                    state[
                        "altitude_ft"
                    ]
                ),

            "vertical_speed_fps":
                float(
                    state[
                        "vertical_speed_fps"
                    ]
                ),

            "heading_error_deg":
                float(
                    state[
                        "heading_error_deg"
                    ]
                ),

            "hover_hold_s":
                float(
                    self.hover_hold_s
                ),

            "physical_aileron_cmd":
                float(
                    state[
                        "physical_aileron_cmd"
                    ]
                ),
        }

    def step(
        self,
        action,
    ):
        used_action = self._apply_action(
            action
        )

        self.steps += 1

        state = snapshot(
            self.fdm,
            self.lat0,
            self.lon0,
            self.mission_heading,
        )

        self.last_state = (
            state.copy()
        )

        # Reproduce the exact bookkeeping order used by the already
        # validated Stage-3 V3 teacher:
        #
        #   raw_cycle(...)
        #   snapshot(...)
        #   env2.forward_distance = true inertial forward position
        #   env2.steps += 1
        #   obs2 = env2._get_obs()
        #
        # env2.steps was already incremented in _apply_action(); the missing
        # forward-distance update was the reproduction bug in the first
        # build_stage3_hybrid_final.py.
        if hasattr(
            self.env2,
            "forward_distance",
        ):
            self.env2.forward_distance = float(
                state[
                    "forward_ft"
                ]
            )

        self.stage2_obs = np.asarray(
            self.env2._get_obs(),
            dtype=np.float32,
        )

        abs_position_error = abs(
            state[
                "position_error_ft"
            ]
        )

        position_improvement = (
            self.previous_abs_position_error
            -
            abs_position_error
        )

        self.previous_abs_position_error = (
            abs_position_error
        )

        # -------------------------------------------------------------
        # REWARD — mission objective only; no runtime teacher action.
        # -------------------------------------------------------------

        reward = 0.0

        # Progress toward the endpoint.
        reward += (
            4.0
            *
            position_improvement
        )

        # Position error.
        reward -= (
            0.025
            *
            abs_position_error
        )

        # Speed should decay as the endpoint approaches.
        desired_speed_for_reward = float(
            np.clip(
                K_POS
                *
                (
                    state[
                        "position_error_ft"
                    ]
                    -
                    BRAKE_LEAD_FT
                ),
                -V_REV_MAX,
                +V_FWD_MAX,
            )
        )

        reward -= (
            1.50
            *
            abs(
                state[
                    "forward_speed_fps"
                ]
                -
                desired_speed_for_reward
            )
        )

        # Lateral geometry.
        reward -= (
            1.25
            *
            abs(
                state[
                    "cross_track_ft"
                ]
            )
        )

        reward -= (
            1.75
            *
            abs(
                state[
                    "lateral_speed_fps"
                ]
            )
        )

        # Altitude / vertical motion.
        reward -= (
            0.80
            *
            abs(
                state[
                    "altitude_ft"
                ]
                -
                TARGET_ALT_FT
            )
        )

        reward -= (
            1.50
            *
            abs(
                state[
                    "vertical_speed_fps"
                ]
            )
        )

        # Heading / attitude.
        reward -= (
            0.10
            *
            abs(
                state[
                    "heading_error_deg"
                ]
            )
        )

        reward -= (
            0.10
            *
            abs(
                math.degrees(
                    state[
                        "pitch_rad"
                    ]
                )
            )
        )

        reward -= (
            0.10
            *
            abs(
                math.degrees(
                    state[
                        "roll_rad"
                    ]
                )
            )
        )

        # Small smoothness term.
        reward -= (
            0.05
            *
            float(
                np.mean(
                    (
                        used_action
                        -
                        self.previous_action
                    )
                    **
                    2
                )
            )
        )

        self.previous_action = (
            used_action.copy()
        )

        hover_now = endpoint_hover_now(
            state
        )

        self.hover_hold_s = (
            self.hover_hold_s
            +
            self.dt
            if hover_now
            else
            0.0
        )

        # Dense endpoint bonus.
        if endpoint_stop_now(
            state
        ):
            reward += 6.0

        if endpoint_lateral_now(
            state
        ):
            reward += 3.0

        if (
            ALT_MIN
            <=
            state[
                "altitude_ft"
            ]
            <=
            ALT_MAX
        ):
            reward += 1.0

        if hover_now:
            reward += 15.0

        terminated = False
        truncated = False
        success = False
        termination_reason = ""

        reason = safety_reason(
            state
        )

        if reason:
            reward -= 300.0
            terminated = True
            termination_reason = (
                reason
            )

        elif (
            self.hover_hold_s
            >=
            STOP_HOLD_SECONDS
        ):
            reward += 500.0
            terminated = True
            success = True
            termination_reason = (
                "endpoint_hover_5s"
            )

        elif (
            self.steps
            >=
            self.max_steps
        ):
            truncated = True
            termination_reason = (
                "stage3_time_limit"
            )

        return (
            stage3_observation(
                state
            ),
            float(
                reward
            ),
            bool(
                terminated
            ),
            bool(
                truncated
            ),
            self._info(
                state,
                success,
                termination_reason,
            ),
        )

    def close(
        self,
    ):
        self._close_current()


# =====================================================================
# TRUE CONTINUOUS EVALUATION
# =====================================================================

def evaluate_controller(
    model=None,
    use_teacher=False,
    detailed=False,
):
    env = (
        HelicopterEnvStage3Hybrid()
    )

    obs, info = env.reset()

    trace = []

    min_alt = +999.0
    max_alt = -999.0
    max_cross = 0.0

    max_abs_pitch = 0.0
    max_abs_roll = 0.0
    max_abs_heading = 0.0

    stop_hold = 0.0
    lateral_hold = 0.0
    full_hover_hold = 0.0

    max_stop_hold = 0.0
    max_lateral_hold = 0.0
    max_full_hover_hold = 0.0

    safe = True
    termination_reason = (
        "stage3_time_limit"
    )

    next_print = 0.0

    final_state = (
        env.last_state.copy()
    )

    for step in range(
        env.max_steps
    ):
        state_before = snapshot(
            env.fdm,
            env.lat0,
            env.lon0,
            env.mission_heading,
        )

        if use_teacher:
            action = locked_teacher_action(
                env.stage2_obs,
                state_before,
            )

        else:
            if model is None:
                env.close()
                raise ValueError(
                    "Need model or use_teacher=True."
                )

            action, _ = (
                model.predict(
                    obs,
                    deterministic=True,
                )
            )

            action = np.asarray(
                action,
                dtype=np.float32,
            ).reshape(
                -1
            )

        action = np.clip(
            action,
            -1.0,
            +1.0,
        ).astype(
            np.float32
        )

        (
            obs,
            _reward,
            terminated,
            truncated,
            info,
        ) = env.step(
            action
        )

        state = (
            env.last_state.copy()
        )

        t = (
            step + 1
        ) * env.dt

        stop_now = endpoint_stop_now(
            state
        )

        lateral_now = endpoint_lateral_now(
            state
        )

        hover_now = endpoint_hover_now(
            state
        )

        stop_hold = (
            stop_hold
            +
            env.dt
            if stop_now
            else
            0.0
        )

        lateral_hold = (
            lateral_hold
            +
            env.dt
            if lateral_now
            else
            0.0
        )

        full_hover_hold = (
            full_hover_hold
            +
            env.dt
            if hover_now
            else
            0.0
        )

        max_stop_hold = max(
            max_stop_hold,
            stop_hold,
        )

        max_lateral_hold = max(
            max_lateral_hold,
            lateral_hold,
        )

        max_full_hover_hold = max(
            max_full_hover_hold,
            full_hover_hold,
        )

        min_alt = min(
            min_alt,
            state[
                "altitude_ft"
            ],
        )

        max_alt = max(
            max_alt,
            state[
                "altitude_ft"
            ],
        )

        max_cross = max(
            max_cross,
            abs(
                state[
                    "cross_track_ft"
                ]
            ),
        )

        max_abs_pitch = max(
            max_abs_pitch,
            abs(
                math.degrees(
                    state[
                        "pitch_rad"
                    ]
                )
            ),
        )

        max_abs_roll = max(
            max_abs_roll,
            abs(
                math.degrees(
                    state[
                        "roll_rad"
                    ]
                )
            ),
        )

        max_abs_heading = max(
            max_abs_heading,
            abs(
                state[
                    "heading_error_deg"
                ]
            ),
        )

        row = {
            "time_s":
                float(
                    t
                ),

            "forward_ft":
                float(
                    state[
                        "forward_ft"
                    ]
                ),

            "position_error_ft":
                float(
                    state[
                        "position_error_ft"
                    ]
                ),

            "forward_speed_fps":
                float(
                    state[
                        "forward_speed_fps"
                    ]
                ),

            "cross_track_ft":
                float(
                    state[
                        "cross_track_ft"
                    ]
                ),

            "lateral_speed_fps":
                float(
                    state[
                        "lateral_speed_fps"
                    ]
                ),

            "altitude_ft":
                float(
                    state[
                        "altitude_ft"
                    ]
                ),

            "vertical_speed_fps":
                float(
                    state[
                        "vertical_speed_fps"
                    ]
                ),

            "heading_error_deg":
                float(
                    state[
                        "heading_error_deg"
                    ]
                ),

            "pitch_deg":
                float(
                    math.degrees(
                        state[
                            "pitch_rad"
                        ]
                    )
                ),

            "roll_deg":
                float(
                    math.degrees(
                        state[
                            "roll_rad"
                        ]
                    )
                ),

            "action0":
                float(
                    action[
                        0
                    ]
                ),

            "action1":
                float(
                    action[
                        1
                    ]
                ),

            "action2":
                float(
                    action[
                        2
                    ]
                ),

            "action3":
                float(
                    action[
                        3
                    ]
                ),

            "physical_aileron_cmd":
                float(
                    state[
                        "physical_aileron_cmd"
                    ]
                ),

            "stop_hold_s":
                float(
                    stop_hold
                ),

            "lateral_hold_s":
                float(
                    lateral_hold
                ),

            "full_hover_hold_s":
                float(
                    full_hover_hold
                ),
        }

        trace.append(
            row
        )

        final_state = (
            state.copy()
        )

        if detailed and (
            t
            >=
            next_print
        ):
            print(
                f"t={t:6.2f}s | "
                f"FWD={state['forward_ft']:7.2f} | "
                f"V={state['forward_speed_fps']:+5.2f} | "
                f"X={state['cross_track_ft']:+6.2f} | "
                f"LAT={state['lateral_speed_fps']:+5.2f} | "
                f"ALT={state['altitude_ft']:7.2f} | "
                f"VS={state['vertical_speed_fps']:+5.2f} | "
                f"A={np.array2string(action, precision=4, floatmode='fixed')} | "
                f"HOLD={full_hover_hold:4.2f}s"
            )

            next_print += (
                1.5
            )

        reason = safety_reason(
            state
        )

        if reason:
            safe = False
            termination_reason = (
                reason
            )
            break

        if (
            full_hover_hold
            >=
            STOP_HOLD_SECONDS
        ):
            termination_reason = (
                "endpoint_hover_5s"
            )
            break

        if truncated:
            termination_reason = (
                info.get(
                    "termination_reason",
                    "stage3_time_limit",
                )
            )
            break

        if (
            terminated
            and
            not bool(
                info.get(
                    "success",
                    False,
                )
            )
        ):
            safe = False
            termination_reason = (
                info.get(
                    "termination_reason",
                    "environment_failure",
                )
            )
            break

    presentation_cross_pass = bool(
        max_cross
        <=
        PRESENTATION_MAX_CROSS_FT
    )

    presentation_altitude_pass = bool(
        min_alt
        >=
        PRESENTATION_ALT_MIN
        and
        max_alt
        <=
        PRESENTATION_ALT_MAX
    )

    persistent_stop_at_final = bool(
        stop_hold
        >=
        STOP_HOLD_SECONDS
    )

    persistent_lateral_at_final = bool(
        lateral_hold
        >=
        STOP_HOLD_SECONDS
    )

    persistent_hover_at_final = bool(
        full_hover_hold
        >=
        STOP_HOLD_SECONDS
    )

    pass_all = bool(
        safe
        and
        presentation_cross_pass
        and
        presentation_altitude_pass
        and
        persistent_stop_at_final
        and
        persistent_lateral_at_final
        and
        persistent_hover_at_final
    )

    result = {
        "pass":
            bool(
                pass_all
            ),

        "safe":
            bool(
                safe
            ),

        "termination_reason":
            str(
                termination_reason
            ),

        "presentation_cross_pass":
            bool(
                presentation_cross_pass
            ),

        "presentation_altitude_pass":
            bool(
                presentation_altitude_pass
            ),

        "persistent_stop_at_final":
            bool(
                persistent_stop_at_final
            ),

        "persistent_lateral_at_final":
            bool(
                persistent_lateral_at_final
            ),

        "persistent_hover_at_final":
            bool(
                persistent_hover_at_final
            ),

        "max_stop_hold_s":
            float(
                max_stop_hold
            ),

        "max_lateral_hold_s":
            float(
                max_lateral_hold
            ),

        "max_full_hover_hold_s":
            float(
                max_full_hover_hold
            ),

        "final_forward_ft":
            float(
                final_state[
                    "forward_ft"
                ]
            ),

        "final_position_error_ft":
            float(
                final_state[
                    "position_error_ft"
                ]
            ),

        "final_forward_speed_fps":
            float(
                final_state[
                    "forward_speed_fps"
                ]
            ),

        "final_cross_ft":
            float(
                final_state[
                    "cross_track_ft"
                ]
            ),

        "final_lateral_speed_fps":
            float(
                final_state[
                    "lateral_speed_fps"
                ]
            ),

        "final_alt_ft":
            float(
                final_state[
                    "altitude_ft"
                ]
            ),

        "final_vs_fps":
            float(
                final_state[
                    "vertical_speed_fps"
                ]
            ),

        "final_heading_error_deg":
            float(
                final_state[
                    "heading_error_deg"
                ]
            ),

        "max_cross_ft":
            float(
                max_cross
            ),

        "min_alt_ft":
            float(
                min_alt
            ),

        "max_alt_ft":
            float(
                max_alt
            ),

        "max_abs_pitch_deg":
            float(
                max_abs_pitch
            ),

        "max_abs_roll_deg":
            float(
                max_abs_roll
            ),

        "max_abs_heading_deg":
            float(
                max_abs_heading
            ),

        "trace":
            trace,
    }

    env.close()

    return result


def print_result(
    label,
    result,
):
    print(
        f"{label:24s} | "
        f"PASS={str(result['pass']):5s} | "
        f"SAFE={str(result['safe']):5s} | "
        f"FWD={result['final_forward_ft']:7.3f} | "
        f"V={result['final_forward_speed_fps']:+6.3f} | "
        f"X={result['final_cross_ft']:+7.3f} | "
        f"LAT={result['final_lateral_speed_fps']:+6.3f} | "
        f"ALT={result['final_alt_ft']:7.3f} | "
        f"XMAX={result['max_cross_ft']:6.3f} | "
        f"ALT=[{result['min_alt_ft']:7.3f},{result['max_alt_ft']:7.3f}] | "
        f"HOLD={result['max_full_hover_hold_s']:5.2f}s"
    )


# =====================================================================
# A — REPRODUCE LOCKED TEACHER
# =====================================================================

rule(
    "A — LOCKED STAGE-3 TEACHER REPRODUCTION"
)

print(
    "Stage-1 model:",
    STAGE1_MODEL_PATH,
)

print(
    "Stage-2 model:",
    STAGE2_MODEL_PATH,
)

print(
    "Stage-3 teacher source:",
    TEACHER_SUMMARY_PATH,
)

print()
print(
    "Teacher lateral activation:",
    LATERAL_ENABLE_FORWARD_FT,
)

print(
    "Teacher lateral trim      :",
    HOVER_TRIM,
)

print(
    "Teacher lateral Kp/Kd     :",
    LATERAL_KP,
    LATERAL_KD,
)

teacher_result = evaluate_controller(
    use_teacher=True,
    detailed=True,
)

print_result(
    "LOCKED TEACHER",
    teacher_result,
)

with (
    RESULT_DIR
    /
    "teacher_reproduction.json"
).open(
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        {
            k: v
            for k, v
            in teacher_result.items()
            if k
            !=
            "trace"
        },
        f,
        indent=2,
    )

if not teacher_result[
    "pass"
]:
    raise RuntimeError(
        "Locked Stage-3 teacher did not reproduce. "
        "Do not distill a non-reproducible teacher."
    )


# =====================================================================
# B — TEACHER DATASET WITH OFF-TRAJECTORY RECOVERY SAMPLES
# =====================================================================

rule(
    "B — COLLECT STAGE-3 TEACHER DATA"
)

dataset_obs = []
dataset_actions = []
dataset_weights = []

dataset_episode_summary = []

for episode in range(
    DATA_ROLLOUTS
):
    env = (
        HelicopterEnvStage3Hybrid()
    )

    obs, _info = env.reset()

    noise_std = float(
        DATA_ACTION_NOISE_STD[
            episode
        ]
    )

    stored = 0
    applied_noise_count = 0
    safety_failure = ""

    for step in range(
        env.max_steps
    ):
        state = (
            env.last_state.copy()
        )

        teacher_action = (
            locked_teacher_action(
                env.stage2_obs,
                state,
            )
        )

        # Weight the endpoint / braking region more strongly.
        abs_pos_error = abs(
            state[
                "position_error_ft"
            ]
        )

        if abs_pos_error <= 20.0:
            weight = 8.0

        elif abs_pos_error <= 70.0:
            weight = 5.0

        else:
            weight = 2.0

        dataset_obs.append(
            np.asarray(
                obs,
                dtype=np.float32,
            ).copy()
        )

        dataset_actions.append(
            np.asarray(
                teacher_action,
                dtype=np.float32,
            ).copy()
        )

        dataset_weights.append(
            float(
                weight
            )
        )

        stored += 1

        applied_action = (
            teacher_action.copy()
        )

        # The label remains exact teacher action.
        # Noise is applied only to the physical rollout so the next state is
        # slightly off the nominal path and the dataset captures recovery.
        if (
            noise_std
            >
            0.0
        ):
            noise = rng.normal(
                loc=0.0,
                scale=noise_std,
                size=4,
            ).astype(
                np.float32
            )

            # Keep rudder unperturbed because the locked yaw command is zero
            # and yaw was already very stable.
            noise[
                3
            ] = 0.0

            applied_action = np.clip(
                applied_action
                +
                noise,
                -1.0,
                +1.0,
            ).astype(
                np.float32
            )

            applied_noise_count += 1

        (
            obs,
            _reward,
            terminated,
            truncated,
            info,
        ) = env.step(
            applied_action
        )

        reason = safety_reason(
            env.last_state
        )

        if reason:
            safety_failure = (
                reason
            )
            break

        # Stop after 5 s of teacher-quality endpoint hover.
        if (
            env.hover_hold_s
            >=
            STOP_HOLD_SECONDS
        ):
            break

        if terminated or truncated:
            break

    dataset_episode_summary.append(
        {
            "episode":
                int(
                    episode + 1
                ),

            "noise_std":
                float(
                    noise_std
                ),

            "stored":
                int(
                    stored
                ),

            "noise_steps":
                int(
                    applied_noise_count
                ),

            "safety_failure":
                str(
                    safety_failure
                ),

            "final_forward_ft":
                float(
                    env.last_state[
                        "forward_ft"
                    ]
                ),

            "final_cross_ft":
                float(
                    env.last_state[
                        "cross_track_ft"
                    ]
                ),

            "final_alt_ft":
                float(
                    env.last_state[
                        "altitude_ft"
                    ]
                ),

            "final_hover_hold_s":
                float(
                    env.hover_hold_s
                ),
        }
    )

    print(
        f"Teacher episode {episode + 1:2d}/{DATA_ROLLOUTS} | "
        f"noise={noise_std:.3f} | "
        f"stored={stored:4d} | "
        f"safe={safety_failure == ''} | "
        f"FWD={env.last_state['forward_ft']:7.2f} | "
        f"X={env.last_state['cross_track_ft']:+6.2f} | "
        f"ALT={env.last_state['altitude_ft']:7.2f} | "
        f"HOLD={env.hover_hold_s:4.2f}s"
    )

    env.close()


dataset_obs = np.asarray(
    dataset_obs,
    dtype=np.float32,
)

dataset_actions = np.asarray(
    dataset_actions,
    dtype=np.float32,
)

dataset_weights = np.asarray(
    dataset_weights,
    dtype=np.float32,
)

print()
print(
    "Dataset observations:",
    dataset_obs.shape,
)

print(
    "Dataset actions     :",
    dataset_actions.shape,
)

with (
    RESULT_DIR
    /
    "dataset_episode_summary.json"
).open(
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        dataset_episode_summary,
        f,
        indent=2,
    )


# =====================================================================
# C — FRESH PPO + BEHAVIOR CLONING
# =====================================================================

rule(
    "C — DISTILL COMPLETE STAGE-3 TEACHER INTO FRESH PPO"
)

bc_env = Monitor(
    HelicopterEnvStage3Hybrid()
)

policy_kwargs = dict(
    activation_fn=nn.Tanh,
    net_arch=dict(
        pi=[
            128,
            128,
        ],
        vf=[
            128,
            128,
        ],
    ),
)

model = PPO(
    "MlpPolicy",
    bc_env,
    policy_kwargs=
        policy_kwargs,
    learning_rate=3e-4,
    n_steps=512,
    batch_size=128,
    n_epochs=5,
    gamma=0.995,
    gae_lambda=0.95,
    clip_range=0.15,
    ent_coef=0.0,
    vf_coef=0.5,
    max_grad_norm=0.5,
    verbose=0,
    seed=SEED,
    device="auto",
)


device = (
    model.device
)

obs_tensor = torch.as_tensor(
    dataset_obs,
    dtype=torch.float32,
    device=device,
)

target_tensor = torch.as_tensor(
    dataset_actions,
    dtype=torch.float32,
    device=device,
)

sample_weight_tensor = (
    torch.as_tensor(
        dataset_weights,
        dtype=torch.float32,
        device=device,
    )
    .reshape(
        -1,
        1,
    )
)


# Elevator / aileron are especially important in Stage 3.
action_loss_weight = (
    torch.as_tensor(
        [
            1.0,
            4.0,
            3.0,
            1.0,
        ],
        dtype=torch.float32,
        device=device,
    )
    .reshape(
        1,
        4,
    )
)


actor_params = []

for name, param in (
    model.policy.named_parameters()
):
    if (
        "mlp_extractor.policy_net"
        in name
        or
        "action_net"
        in name
    ):
        actor_params.append(
            param
        )


if not actor_params:
    raise RuntimeError(
        "Could not locate PPO actor parameters."
    )


bc_optimizer = torch.optim.Adam(
    actor_params,
    lr=BC_LR,
)

indices = np.arange(
    len(
        dataset_obs
    )
)

best_bc_loss = float(
    "inf"
)

best_actor_state = None

for epoch in range(
    1,
    BC_EPOCHS + 1,
):
    rng.shuffle(
        indices
    )

    epoch_loss = 0.0
    batches = 0

    for start in range(
        0,
        len(
            indices
        ),
        BC_BATCH_SIZE,
    ):
        idx_np = indices[
            start:
            start
            +
            BC_BATCH_SIZE
        ]

        idx = torch.as_tensor(
            idx_np,
            dtype=torch.long,
            device=device,
        )

        batch_obs = (
            obs_tensor[
                idx
            ]
        )

        batch_target = (
            target_tensor[
                idx
            ]
        )

        batch_weight = (
            sample_weight_tensor[
                idx
            ]
        )

        actor_features = (
            model.policy.extract_features(
                batch_obs,
                model.policy.pi_features_extractor,
            )
        )

        latent_pi = (
            model.policy
            .mlp_extractor
            .forward_actor(
                actor_features
            )
        )

        pred = (
            model.policy
            .action_net(
                latent_pi
            )
        )

        squared = (
            pred
            -
            batch_target
        ) ** 2

        loss = (
            squared
            *
            action_loss_weight
            *
            batch_weight
        ).mean()

        bc_optimizer.zero_grad(
            set_to_none=True
        )

        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            actor_params,
            1.0,
        )

        bc_optimizer.step()

        epoch_loss += float(
            loss.detach().cpu()
        )

        batches += 1

    epoch_loss /= max(
        1,
        batches,
    )

    if (
        epoch_loss
        <
        best_bc_loss
    ):
        best_bc_loss = (
            epoch_loss
        )

        best_actor_state = {
            name:
                param.detach().clone()
            for name, param in
            model.policy.named_parameters()
            if (
                "mlp_extractor.policy_net"
                in name
                or
                "action_net"
                in name
            )
        }

    if (
        epoch == 1
        or
        epoch % 40
        ==
        0
        or
        epoch
        ==
        BC_EPOCHS
    ):
        print(
            f"BC epoch {epoch:4d}/{BC_EPOCHS} | "
            f"loss={epoch_loss:.8f} | "
            f"best={best_bc_loss:.8f}"
        )


if best_actor_state is None:
    raise RuntimeError(
        "BC did not produce an actor state."
    )


with torch.no_grad():
    for name, param in (
        model.policy.named_parameters()
    ):
        if (
            name
            in
            best_actor_state
        ):
            param.copy_(
                best_actor_state[
                    name
                ]
            )

    if hasattr(
        model.policy,
        "log_std",
    ):
        model.policy.log_std.fill_(
            math.log(
                RL_EXPLORATION_STD
            )
        )


model.save(
    str(
        BC_MODEL_PATH
    )
)

bc_env.close()

print()
print(
    "Saved BC warm-start:",
    str(
        BC_MODEL_PATH
    )
    +
    ".zip"
)


# =====================================================================
# D — TEACHER-OFF BC VALIDATION
# =====================================================================

rule(
    "D — TEACHER-OFF BC VALIDATION"
)

bc_result = evaluate_controller(
    model=model,
    use_teacher=False,
    detailed=True,
)

print_result(
    "BC PPO",
    bc_result,
)

with (
    RESULT_DIR
    /
    "bc_validation.json"
).open(
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        {
            k: v
            for k, v in
            bc_result.items()
            if k
            !=
            "trace"
        },
        f,
        indent=2,
    )


if not bc_result[
    "pass"
]:
    rule(
        "BC DISTILLATION NOT ACCEPTED"
    )

    print(
        "Teacher reproduction passed, but the Stage-3 PPO actor did not "
        "imitate it accurately enough with teacher OFF."
    )

    print(
        "No PPO RL fine-tuning will be claimed or started."
    )

    raise RuntimeError(
        "Teacher-off Stage-3 BC validation failed."
    )


# =====================================================================
# E — GENUINE PPO RL FINE-TUNING
# =====================================================================

rule(
    "E — PPO REINFORCEMENT-LEARNING FINE-TUNING"
)

print(
    "Runtime teacher in RL environment : OFF"
)

print(
    "Runtime classical controller      : OFF"
)

print(
    "Reward-based PPO updates           : ON"
)

rl_results = []

for idx, (
    lr,
    timesteps,
) in enumerate(
    RL_CANDIDATES,
    start=1,
):
    print()
    print(
        f"RL candidate {idx}/{len(RL_CANDIDATES)} | "
        f"lr={lr:.1e} | "
        f"steps={timesteps}"
    )

    train_env = Monitor(
        HelicopterEnvStage3Hybrid()
    )

    candidate = PPO.load(
        str(
            BC_MODEL_PATH
        )
        +
        ".zip",
        env=train_env,
        device="auto",
    )

    candidate.learning_rate = float(
        lr
    )

    candidate.lr_schedule = (
        lambda progress_remaining,
        lr=float(
            lr
        ):
        lr
    )

    candidate.ent_coef = 0.0
    candidate.target_kl = (
        0.005
    )

    with torch.no_grad():
        if hasattr(
            candidate.policy,
            "log_std",
        ):
            candidate.policy.log_std.fill_(
                math.log(
                    RL_EXPLORATION_STD
                )
            )

    candidate.learn(
        total_timesteps=int(
            timesteps
        ),
        reset_num_timesteps=True,
        progress_bar=True,
    )

    train_env.close()

    candidate_path = (
        MODEL_DIR
        /
        (
            "AH1S_STAGE3_RL_"
            f"{idx:02d}_"
            f"{timesteps}STEPS"
        )
    )

    candidate.save(
        str(
            candidate_path
        )
    )

    result = evaluate_controller(
        model=candidate,
        use_teacher=False,
        detailed=False,
    )

    result[
        "learning_rate"
    ] = float(
        lr
    )

    result[
        "timesteps"
    ] = int(
        timesteps
    )

    result[
        "model_path"
    ] = (
        str(
            candidate_path
        )
        +
        ".zip"
    )

    rl_results.append(
        (
            result,
            candidate,
        )
    )

    print_result(
        f"RL {idx}",
        result,
    )


# =====================================================================
# SELECT ONLY A PASSING RL CANDIDATE
# =====================================================================

def rl_selection_key(
    item,
):
    result = item[
        0
    ]

    return (
        0
        if result[
            "pass"
        ]
        else
        1,

        result[
            "max_cross_ft"
        ],

        abs(
            result[
                "final_position_error_ft"
            ]
        ),

        abs(
            result[
                "final_forward_speed_fps"
            ]
        ),

        abs(
            result[
                "final_cross_ft"
            ]
        ),

        abs(
            result[
                "final_lateral_speed_fps"
            ]
        ),

        abs(
            result[
                "final_alt_ft"
            ]
            -
            TARGET_ALT_FT
        ),
    )


rl_results.sort(
    key=
        rl_selection_key
)


best_rl_result, best_rl_model = (
    rl_results[
        0
    ]
)


with (
    RESULT_DIR
    /
    "rl_candidate_summary.json"
).open(
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        [
            {
                k: v
                for k, v in
                result.items()
                if k
                !=
                "trace"
            }
            for result, _model
            in rl_results
        ],
        f,
        indent=2,
    )


if not best_rl_result[
    "pass"
]:
    rule(
        "NO PPO-RL CANDIDATE PASSED"
    )

    print(
        "The BC policy remains a passing distilled policy, but no reward-based "
        "PPO refinement is accepted as final."
    )

    print(
        "Do NOT label the Stage-3 model 'hybrid final' yet."
    )

    raise RuntimeError(
        "No passing Stage-3 PPO RL candidate."
    )


# =====================================================================
# F — FINAL FRESH CONTINUOUS TEACHER-OFF VALIDATION
# =====================================================================

rule(
    "F — FINAL TRUE CONTINUOUS TEACHER-OFF VALIDATION"
)

print(
    "Stage-1 teacher             : OFF"
)

print(
    "Stage-2 teacher             : OFF"
)

print(
    "Stage-3 teacher             : OFF"
)

print(
    "Stage-3 altitude controller : OFF"
)

print(
    "Stage-3 longitudinal ctrl   : OFF"
)

print(
    "Stage-3 lateral controller  : OFF"
)

print(
    "Stage-3 runtime             : PPO policy only"
)

print(
    "PPO RL fine-tuning          : YES"
)

print(
    "Distillation               : YES"
)

final_result = evaluate_controller(
    model=best_rl_model,
    use_teacher=False,
    detailed=True,
)

print_result(
    "FINAL HYBRID PPO",
    final_result,
)


# Save final trace.
if final_result[
    "trace"
]:
    trace_path = (
        RESULT_DIR
        /
        "final_trace.csv"
    )

    with trace_path.open(
        "w",
        newline="",
        encoding="utf-8",
    ) as f:
        writer = csv.DictWriter(
            f,
            fieldnames=list(
                final_result[
                    "trace"
                ][
                    0
                ].keys()
            ),
        )

        writer.writeheader()
        writer.writerows(
            final_result[
                "trace"
            ]
        )


final_summary = {
    "method":
        (
            "locked teacher -> behavior cloning / policy distillation -> "
            "reward-based PPO fine-tuning -> teacher-off continuous validation"
        ),

    "stage1_model":
        str(
            STAGE1_MODEL_PATH
        ),

    "stage2_model":
        str(
            STAGE2_MODEL_PATH
        ),

    "stage3_observation_dim":
        14,

    "stage3_observation_contains": [
        "altitude_error",
        "vertical_speed",
        "forward_position_error",
        "forward_speed",
        "cross_track",
        "lateral_speed",
        "sin_heading_error",
        "cos_heading_error",
        "pitch",
        "roll",
        "roll_rate",
        "pitch_rate",
        "yaw_rate",
        "rotor_rpm",
    ],

    "teacher_parameters": {
        "lateral_enable_forward_ft":
            float(
                LATERAL_ENABLE_FORWARD_FT
            ),

        "hover_trim":
            float(
                HOVER_TRIM
            ),

        "lateral_kp":
            float(
                LATERAL_KP
            ),

        "lateral_kd":
            float(
                LATERAL_KD
            ),
    },

    "bc_best_loss":
        float(
            best_bc_loss
        ),

    "selected_rl_learning_rate":
        float(
            best_rl_result[
                "learning_rate"
            ]
        ),

    "selected_rl_timesteps":
        int(
            best_rl_result[
                "timesteps"
            ]
        ),

    "final": {
        k: v
        for k, v in
        final_result.items()
        if k
        !=
        "trace"
    },
}


with (
    RESULT_DIR
    /
    "final_summary.json"
).open(
    "w",
    encoding="utf-8",
) as f:
    json.dump(
        final_summary,
        f,
        indent=2,
    )


if not final_result[
    "pass"
]:
    rule(
        "FINAL CONTINUOUS VALIDATION FAILED"
    )

    print(
        "A PPO RL candidate passed its first evaluation but did not reproduce "
        "on the final fresh validation. No final model is saved."
    )

    raise RuntimeError(
        "Final Stage-3 teacher-off validation failed."
    )


best_rl_model.save(
    str(
        FINAL_MODEL_PATH
    )
)


rule(
    "STAGE 3 HYBRID FINAL — LOCKED"
)

print(
    "TRUE continuous mission segment:"
)

print(
    "Stage1 takeoff -> Stage2 cruise -> Stage3 endpoint stop/hover"
)

print()
print(
    "Stage-3 teacher at FINAL runtime : OFF"
)

print(
    "Stage-3 classical controllers    : OFF"
)

print(
    "Stage-3 PPO RL fine-tuning       : YES"
)

print(
    "Stage-3 policy distillation      : YES"
)

print(
    "Mapped actuator repair           : YES"
)

print()
print(
    "FINAL MODEL:",
    str(
        FINAL_MODEL_PATH
    )
    +
    ".zip"
)

print(
    "RESULT SUMMARY:",
    str(
        RESULT_DIR
        /
        "final_summary.json"
    )
)

print(
    "RESULT TRACE:",
    str(
        RESULT_DIR
        /
        "final_trace.csv"
    )
)

print()
print(
    "NEXT: back up Stage-3 final, then identify and calibrate Stage-4 "
    "vertical descent / landing."
)
